services:
  chudder:
    #Use "chudder-rootless" for rootless docker setups, otherwise use "chudder"
    image: ghcr.io/jentejan/chudder:latest
    ports:
      - 80:80
    environment:
      - BASE_URL=https://server-url #OPTIONAL: Locks the Chudder front-end to a certain jellyfin server
      - SEERR_BASE_URL=https://seerr-url #OPTIONAL: Presets Seerr base URL
      - SEERR_HEADER={"key":"value"} #OPTIONAL: JSON object string of Seerr headers
      - CHUDDER_WEBPATH=/ #OPTIONAL: Configures a subpath to run Chudder at
